#!/usr/bin/env bash
# build-agent-rules.sh — compile base/CLAUDE.base.md into other agents' formats.
#
# base/CLAUDE.base.md is the single source of truth. Everything under dist/ is
# GENERATED from it and must never be hand-edited: tests/test-agent-rules.sh
# regenerates and diffs, so a manual edit fails the gate.
#
#   AGENTS.md            — read by Codex, Cursor, Copilot, Gemini CLI, Zed and
#                          ~20 other tools (spec stewarded by the Agentic AI
#                          Foundation). Carries the full conventions.
#   .cursor/rules/*.mdc  — Cursor-native. Split so each convention is attached
#                          to the files it actually governs via `globs`.
#                          Legacy .cursorrules is deliberately NOT emitted: it
#                          is silently ignored in Cursor Agent mode.
#
# Usage: scripts/build-agent-rules.sh [outdir]     (default: dist)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/dist}"
BASE="$ROOT/base/CLAUDE.base.md"
[ -f "$BASE" ] || { echo "error: $BASE not found" >&2; exit 1; }

GENERATED_NOTE="Generated by scripts/build-agent-rules.sh from base/CLAUDE.base.md — do not edit by hand."

# Print one '## ' section (heading included) from the source file.
section() {
  awk -v want="$1" '
    index($0, "## ") == 1 { keep = ($0 == want) }
    keep { print }
  ' "$BASE"
}

# Everything from the first '## ' onward — i.e. the conventions without the
# base file's own title and Claude-specific preamble.
body() {
  awk 'index($0, "## ") == 1 { p = 1 } p { print }' "$BASE"
}

emit_mdc() {
  # emit_mdc <file> <description> <globs-or-empty> <always> <heading>...
  local file="$1" desc="$2" globs="$3" always="$4"; shift 4
  {
    printf -- '---\n'
    printf 'description: %s\n' "$desc"
    [ -n "$globs" ] && printf 'globs: %s\n' "$globs"
    printf 'alwaysApply: %s\n' "$always"
    printf -- '---\n\n'
    printf '<!-- %s -->\n' "$GENERATED_NOTE"
    for h in "$@"; do printf '\n'; section "## $h"; done
  } > "$file"
}

mkdir -p "$OUT" "$OUT/.cursor/rules"

# --- AGENTS.md: the full conventions, one file, maximum reach ----------------
{
  printf '# Data engineering conventions (de-harness)\n\n'
  printf '<!-- %s -->\n\n' "$GENERATED_NOTE"
  printf 'These rules apply to pipeline code in this repository, on top of general\n'
  printf 'software engineering practice. Anything this project defines for itself\n'
  printf 'wins over these rules.\n\n'
  body
} > "$OUT/AGENTS.md"

# --- Cursor rules: each convention attached to the files it governs ----------
# Partitioned so every '## ' section appears in exactly one .mdc — no rule is
# duplicated across files, and none is dropped (both asserted by the tests).
emit_mdc "$OUT/.cursor/rules/de-harness-base.mdc" \
  'Core data engineering conventions: idempotency, verification, PII, git safety.' \
  '' 'true' \
  'Operating principle' \
  'Idempotency by default' \
  'Verification — "done" means proven' \
  'PII and sensitive data' \
  'Git and safety guardrails' \
  'No AI co-author trailers'

emit_mdc "$OUT/.cursor/rules/de-harness-sql-models.mdc" \
  'Conventions for SQL transforms and dbt models: schema contracts, data quality tests, destructive SQL.' \
  '["**/*.sql", "**/schema.yml", "**/sources.yml", "**/dbt_project.yml"]' 'false' \
  'Schema contracts at every boundary' \
  'Data quality checks are part of the gate' \
  'No destructive SQL without explicit human confirmation'

emit_mdc "$OUT/.cursor/rules/de-harness-orchestration.mdc" \
  'Conventions for orchestrated pipelines (Airflow/Dagster): backfills, observability, cost.' \
  '["**/dags/**/*.py", "**/dagster/**/*.py", "**/definitions.py"]' 'false' \
  'Backfills are a first-class, reviewed operation' \
  'Observability is not optional' \
  'Cost awareness'

echo "Wrote:"
find "$OUT" -type f \( -name '*.md' -o -name '*.mdc' \) | sed "s|^$OUT|  dist|" | sort
